### ISSUE TITLE
Did this project ever get off the ground?

### ISSUE THREAD

**Issue by darthmolen** [dealproc/Durandal.PDFViewer#1]
I'm curious because we have a client asking and needing this very thing.

**Comment by dealproc** [comment]
No, unfortunately i went another route.  Not sure if I'll come back to this or not long term.

**Comment by dealproc** [comment]
@darthmolen Just an FYI... if you want to make a clone of this.. I'm going to kill this project in the next week or so... it's just bitrot for me now, and I don't think i have gems that will assist me with future projects, so I see no reason to keep it.
